# 1. metadata
title: Kat Donnally Studio
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com

description: >-
  Ceramicist located in Richmond, Virginia, making
  functional yet stylish pieces.

# 2. build settings
incremental: true
markdown: kramdown

exclude:
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - assets/python
  - node_modules
  - vendor

permalink: /:year/:month/:title/

collections_dir: collections

# example setup
# collections:
#  collection-name:
#    output: true
#    permalink: /:collection/:slug/

collections:
  bowls:
  jars:
  mugs:
  planters:
  vases:

# 3. assets
sass:
  sass_dir: "assets/css/_sass"

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "pages"
    values:
      order: 10
  - scope:
      path: ""
    values:
      layout: default

# defaults explained:
# 1. static images are in assets/img/*
# 2. by default, any pages/* document has
#    'order' var of value '10'
# 3. all pages have no-style-2 layout unless
#    otherwise specified